version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "19:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-redux
    versions:
    - 7.2.2
    - 7.2.3
  - dependency-name: redux
    versions:
    - 4.0.5
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
    - 4.0.3
  - dependency-name: eslint
    versions:
    - 6.8.0
  - dependency-name: eslint-loader
    versions:
    - 4.0.2
  - dependency-name: acorn
    versions:
    - 5.7.4
  - dependency-name: lodash
    versions:
    - 4.17.20
    - 4.17.21
  - dependency-name: handlebars
    versions:
    - 4.7.6
    - 4.7.7
  - dependency-name: elliptic
    versions:
    - 6.5.3
    - 6.5.4
  - dependency-name: axios
    versions:
    - 0.21.1
  - dependency-name: http-proxy
    versions:
    - 1.18.1
  - dependency-name: dot-prop
    versions:
    - 4.2.1
