export const ADD_GROUPS_LOADING = 'ADD_GROUPS_LOADING';
export const ADD_GROUPS_ERROR = 'ADD_GROUPS_ERROR';
export const ADD_GROUPS_SUCCESS = 'ADD_GROUPS_SUCCESS';

export const GET_GROUPS_LOADING = 'GET_GROUPS_LOADING';
export const GET_GROUPS_ERROR = 'GET_GROUPS_ERROR';
export const GET_GROUPS_SUCCESS = 'GET_GROUPS_SUCCESS';
