version: 2
jobs:
  test:
    docker:
      - image: circleci/node:current
    steps:
      - checkout
      - run: npm install && npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
